"""Config file generation.

The generated .vcfg deliberately matches the house style of the configs it
sits beside: banner comments, ECHO markers around each section, and a comment
column so values line up. A generated file that looks foreign is a file people
stop trusting.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple

from .backup import BackupSession
from .kb import KnowledgeBase
from .profile import Profile

COMMENT_COLUMN = 44
BANNER = "=" * 45
RULE = "-" * 26

GENERATED_MARKER = "// GENERATED BY cs2-autoconfig -- DO NOT EDIT BY HAND"


def _setting(name: str, value: str, comment: str) -> str:
    """One convar line with the comment padded to the house column."""
    body = f'{name} "{value}"'
    padding = max(1, COMMENT_COLUMN - len(body))
    return f"{body}{' ' * padding}// {comment}"


def render_cfg(profile: Profile, kb: KnowledgeBase, filename: str = "autoperf.vcfg") -> str:
    """Build the generated performance config."""
    machine = profile.machine
    gpu = machine.gpu.name if machine.gpu else "unknown GPU"
    cpu = machine.cpu.name if machine.cpu else "unknown CPU"
    display = machine.primary_display

    # Sort the convars into sections first, so the banner can name the
    # sections that actually exist rather than a fixed optimistic list.
    frame_rate: List[Tuple[str, str, str]] = []
    network: List[Tuple[str, str, str]] = []
    visibility: List[Tuple[str, str, str]] = []
    for name, value, reason in profile.convars:
        if name == "rate":
            network.append((name, value, reason))
        elif name.startswith("r_player"):
            visibility.append((name, value, reason))
        else:
            frame_rate.append((name, value, reason))

    present = [
        title for title, rows in
        (("FRAME RATE", frame_rate), ("NETWORK", network), ("VISIBILITY", visibility))
        if rows
    ]

    lines: List[str] = [
        f"// {BANNER}",
        f"// PERFORMANCE SETTINGS - {filename}",
        "// " + " | ".join(present),
        f"// {BANNER}",
        "//",
        GENERATED_MARKER,
        f"// Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"// Machine   {cpu}",
        f"//           {gpu}, {machine.ram_gb:g} GB RAM",
    ]
    if display:
        lines.append(f"//           {display.width}x{display.height} @ {display.refresh} Hz")
    lines += [
        f"// Profile   tier {profile.tier}, {profile.intent} intent",
        f"// Estimate  ~{profile.estimated_fps} fps against a {profile.target_fps} fps target",
        f"// Limit     {profile.bottleneck}",
        "//",
        "// Picture quality is NOT set here. CS2 keeps it in cs2_video.txt under",
        "// your Steam userdata folder, and ignores these convars if you try. Run",
        "// cs2cfg apply to write that file; this one only carries what a config",
        "// can actually change.",
        f"// {BANNER}",
        "",
        "ECHO",
        "ECHO",
        'ECHO "LOADING AUTO-TUNED PERFORMANCE SETTINGS"',
        "ECHO",
        "ECHO",
        "",
        f"// {RULE}",
        "// FRAME RATE",
        f"// {RULE}",
    ]

    for name, value, reason in frame_rate:
        lines.append(_setting(name, value, reason))

    lines += [
        "",
        'ECHO "FRAME RATE SETTINGS LOADED SUCCESSFULLY!"',
        "ECHO",
    ]

    if network:
        lines += ["", f"// {RULE}", "// NETWORK", f"// {RULE}"]
        for name, value, reason in network:
            lines.append(_setting(name, value, reason))
        lines += ["", 'ECHO "NETWORK SETTINGS LOADED SUCCESSFULLY!"', "ECHO"]

    if visibility:
        lines += ["", f"// {RULE}", "// VISIBILITY", f"// {RULE}"]
        for name, value, reason in visibility:
            lines.append(_setting(name, value, reason))
        lines += ["", 'ECHO "VISIBILITY SETTINGS LOADED SUCCESSFULLY!"', "ECHO"]

    lines += [
        "",
        f"// {RULE}",
        "// PICTURE QUALITY WRITTEN TO cs2_video.txt",
        f"// {RULE}",
        "// Recorded here so the config explains the whole picture, even though",
        "// these values live in a different file:",
    ]
    for key in sorted(profile.video):
        value = profile.video[key]
        lines.append(f"//   {kb.ui_name(key):<32} {kb.label(key, value)}")

    lines += [
        "",
        f"// {RULE}",
        "// FINALIZATION",
        f"// {RULE}",
        "ECHO",
        f'ECHO "FILE {filename} HAS LOADED SUCCESSFULLY!"',
        "ECHO",
        "",
    ]
    return "\n".join(lines)


def render_launch_notes(profile: Profile, launch_line: str, removed, added) -> str:
    """A human-readable companion to the launch options, in the same spirit
    as a hand-kept launch_options.txt."""
    lines = [
        "=" * 70,
        "CS2 LAUNCH OPTIONS - generated by cs2-autoconfig",
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "=" * 70,
        "",
        "Paste this into Steam > right-click Counter-Strike 2 > Properties > Launch Options",
        "(the tool can write it for you with `cs2cfg apply`, with Steam closed):",
        "",
        f"    {launch_line}",
        "",
    ]

    if removed:
        lines += ["-" * 70, "REMOVED", "-" * 70, ""]
        for option, reason in removed:
            lines.append(f"  {option}")
            for chunk in _wrap(reason, 66):
                lines.append(f"      {chunk}")
            lines.append("")

    if added:
        lines += ["-" * 70, "ADDED", "-" * 70, ""]
        for option, reason in added:
            lines.append(f"  {option}")
            for chunk in _wrap(reason, 66):
                lines.append(f"      {chunk}")
            lines.append("")

    lines += [
        "-" * 70,
        "NOTE",
        "-" * 70,
        "",
        "Steam stores launch options in localconfig.vdf and rewrites that file",
        "when it exits. Editing it while Steam is running loses the change, which",
        "is why the tool refuses to write unless Steam is closed.",
        "",
    ]
    return "\n".join(lines)


def _wrap(text: str, width: int) -> List[str]:
    words = text.split()
    out: List[str] = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            out.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        out.append(current)
    return out


def write_text_file(path: Path, content: str, session: Optional[BackupSession] = None) -> Path:
    """Write a file, backing up whatever was there first."""
    path = Path(path)
    if session is not None:
        session.add(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def ensure_exec_line(
    autoexec: Path,
    exec_target: str,
    session: Optional[BackupSession] = None,
) -> str:
    """Add an ``exec`` for the generated config to an existing autoexec.

    Idempotent: if the line is already there in any form, nothing changes.
    Appended at the end so it wins over anything set earlier in the file.
    """
    autoexec = Path(autoexec)
    if not autoexec.exists():
        return f"autoexec not found at {autoexec}; add `exec \"{exec_target}\"` yourself"

    text = autoexec.read_text(encoding="utf-8", errors="replace")
    needle = exec_target.replace("\\", "/").lower()
    if needle in text.replace("\\", "/").lower():
        return "already referenced; left alone"

    if session is not None:
        session.add(autoexec)

    ending = "\r\n" if "\r\n" in text else "\n"
    block = ending.join([
        "",
        "// ---------------------------------------------",
        "// Auto-tuned performance settings (cs2-autoconfig)",
        "ECHO",
        'ECHO "Loading AUTO-TUNED PERFORMANCE Settings"',
        f'exec "{exec_target}"',
        'ECHO "AUTO-TUNED PERFORMANCE Settings Loaded Successfully"',
        "ECHO",
        "// ---------------------------------------------",
        "",
    ])

    if not text.endswith(("\n", "\r")):
        text += ending
    autoexec.write_text(text + block, encoding="utf-8")
    return f"appended exec line to {autoexec.name}"


def strip_generated_block(autoexec: Path, session: Optional[BackupSession] = None) -> bool:
    """Remove a block this tool previously appended. Used by `revert`."""
    autoexec = Path(autoexec)
    if not autoexec.exists():
        return False
    text = autoexec.read_text(encoding="utf-8", errors="replace")
    pattern = re.compile(
        r"\r?\n// -+\r?\n// Auto-tuned performance settings \(cs2-autoconfig\).*?// -+\r?\n",
        re.DOTALL,
    )
    new_text, count = pattern.subn("\n", text)
    if not count:
        return False
    if session is not None:
        session.add(autoexec)
    autoexec.write_text(new_text, encoding="utf-8")
    return True
